export const GET_ALL_CONNECTED_USERS = 'GET_ALL_CONNECTED_USERS';
export const GET_ALL_CONVERSATIONS = 'GET_ALL_CONVERSATIONS';
export const GET_CONVERSATION = 'GET_CONVERSATION';
export const GET_MESSAGES = 'GET_MESSAGES';
export const CHANGE_PROFILE_PICTURE = 'CHANGE_PROFILE_PICTURE';
export const SET_FILE_PROGRESS = 'SET_FILE_PROGRESS';
export const GET_ERROR = 'GET_ERROR';
